"""Regenerate a run's end-of-run artifacts (fill_curve, front_profile, GIF,
report.md) from its frozen files — newest checkpoint + state42.npz + metrics.csv
+ run_meta.json — without re-simulating. Intended for runs whose simulation
completed but whose post-processing did not (e.g. an interrupted job).

Usage: uv run python demo/underfill_mt/finish_run.py output/run ["stop reason"]
"""

from __future__ import annotations

import csv
import hashlib
import json
import re
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
from geometry import build_gap_mask, load_package
from underfill_demo import fill_fraction, front_profile, nu

from bob import color3d, porous3d
from bob.utils import viz

HERE = Path(__file__).resolve().parent


def main():
    out = Path(sys.argv[1])
    if not out.is_absolute():
        out = HERE / out
    reason = sys.argv[2] if len(sys.argv) > 2 else "finished (report regenerated post-hoc)"
    meta = json.loads((out / "run_meta.json").read_text())
    solver, extra = meta["solver"], meta.get("extra") or {}
    dx = extra.get("dx_mm", 0.03)
    bump_shape = extra.get("bump_shape", "sphere")
    margin = extra.get("margin_mm", 0.0)

    pkg = load_package()
    nz, ny, nx = meta["geometry"]["shape"]
    buffer = (nx - round(pkg["body"]["D"] / dx)) // 2
    solid_np, info = build_gap_mask(pkg, dx=dx, buffer_in=buffer, buffer_out=buffer, bump_shape=bump_shape, margin_mm=margin)
    assert hashlib.sha256(np.ascontiguousarray(solid_np)).hexdigest() == meta["geometry"]["sha256"], "geometry mismatch"
    xs, ys, chip_x, chip_y = info["xs"], info["ys"], info["chip_x"], info["chip_y"]

    cks = sorted(out.glob("ckpt_step*_sat*.npz"), key=lambda p: int(re.search(r"step(\d+)", p.name).group(1)))
    ck = np.load(cks[-1])
    state = color3d.State(jnp.asarray(ck["fR"]), jnp.asarray(ck["fB"]))
    step = int(ck["step"])
    fill = fill_fraction(state, solid_np, chip_x, chip_y)

    with open(out / "metrics.csv", encoding="utf-8") as fh:
        rows = [{"step": int(r["step"]), "fill": float(r["fill"])} for r in csv.DictReader(fh)]

    title = (
        f"MT6225A underfill (theta={solver['theta']:.0f} deg, sigma={solver['sigma']:g}, dx={dx:g} mm, "
        f"{bump_shape} bumps, margin {margin:g} mm, capillary dP=0)"
    )

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot([r["step"] for r in rows], [100 * r["fill"] for r in rows], "-o", ms=3)
    ax.axhline(42.0, color="gray", ls="--", lw=1, label="paper Fig. 8 snapshot (42 %)")
    ax.set_xlabel("step")
    ax.set_ylabel("chip gap fill (%)")
    ax.set_title(title)
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(out / "fill_curve.png", dpi=130)
    plt.close(fig)

    ys_chip = ys[chip_y]
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.plot(front_profile(state, solid_np, chip_x, chip_y, xs), ys_chip, "-", lw=1.2, label=f"final (step {step}, {fill * 100:.0f} %)")
    snap_txt = ""
    if (out / "state42.npz").exists():
        s42 = np.load(out / "state42.npz")
        st42 = color3d.State(jnp.asarray(s42["fR"]), jnp.asarray(s42["fB"]))
        ax.plot(
            front_profile(st42, solid_np, chip_x, chip_y, xs), ys_chip, "-", lw=1.2, color="tab:orange",
            label=f"at 42 % (step {int(s42['step'])})",
        )
        snap_txt = f" | 42 % snapshot at step {int(s42['step'])}"
    span = 10.4 / 2 + 0.15
    for yb in (-span, span):
        ax.axhline(yb, color="gray", ls=":", lw=1)
    ax.set_xlabel("melt-front position x (mm)")
    ax.set_ylabel("y (mm)")
    ax.set_title("Melt-front profile x_front(y)")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(out / "front_profile.png", dpi=130)
    plt.close(fig)

    frame_paths = sorted((out / "frames").glob("frame_*.png"), key=lambda q: int(q.stem.split("_")[1]))
    if len(frame_paths) > 200:
        idx = np.unique(np.linspace(0, len(frame_paths) - 1, 200).round().astype(int))
        frame_paths = [frame_paths[i] for i in idx]
    if frame_paths:
        viz.write_gif(frame_paths, out / "underfill.gif", 12)

    connected = porous3d.connected_to_inlet(state, solid_np)
    (out / "report.md").write_text(
        f"# {title}\n\n"
        f"- Geometry mt6225a_package_geometry.json | dx {dx:g} mm | domain {nz}x{ny}x{nx} "
        f"| gap porosity {info['gap_porosity']:.3f} | 264 {bump_shape} balls\n"
        f"- Capillary-driven (Zou-He dP=0 inlet+outlet), theta {solver['theta']:.0f} deg on all walls "
        f"(paper case 3: uniform wettability), sigma {solver['sigma']:g}, beta {solver['beta']:g}, "
        f"nu_red {nu(solver['omega']):.3f} / nu_blue {nu(solver['omega2']):.3f} (encapsulant more viscous)\n"
        f"- Steps {step} | stop: {reason} | (report regenerated by finish_run.py; timing in run_meta.json)\n\n"
        f"## Result\n\n"
        f"- Chip fill {rows[0]['fill']:.3f} -> {fill:.3f}{snap_txt}\n"
        f"- Inlet-connected red fraction {connected:.4f}\n"
        f"- Artifacts: frames/ + underfill.gif (top-view melt front), fill_curve.png, front_profile.png\n",
        encoding="utf-8",
    )
    print(f"finished {out.name}: fill {rows[0]['fill']:.3f} -> {fill:.3f} at step {step} ({reason})")


if __name__ == "__main__":
    main()
